projet_symfony/src/Entity/Articles.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ArticlesRepository;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
#[ORM\HasLifecycleCallbacks]

class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    private $intro;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'string', length: 255)]
    private $image;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private $Author;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

  

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
     #[ORM\PrePersist]
    public function initSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->getTitle(). time( ) . hash("sha1",$this->getIntro()) );
        }
    }
    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTime();
    }

    public function getAuthor(): ?user
    {
        return $this->Author;
    }

    public function setAuthor(?user $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
  
}

projet_symfony/templates/partials/article.html.twig
<h1 class="d-flex justify-content-center">Articles</h1>
<div class="d-flex flex-wrap justify-content-around">
{% for art in article %}


<div class="card" style="width: 18rem;">
  <img src="{{art.image}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{art.title}}</h5>
    <p class="card-text">{{art.content}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{art.intro}}</li>
    <li class="list-group-item">{{ art.createdAt |date('d-m-Y') }}</li>
    <li class="list-group-item"></li>
  </ul>
  <div class="card-body">
    <a href="{{ path('app_single_article', {"slug": art.slug}) }}" class="card-link">Card link</a>

    <a href="#" class="card-link">Auteur: {{art.author.username}}</a>

  </div>
</div>

{% endfor %}
</div>

projet_symfony/templates/partials/header.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" href="{{ path('app_home') }}">Read And Write</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
                <a class="nav-link" href="{{ path('app_home') }}">
                    <i class="fa fa-home"></i>
                    Accueil

                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('app_article') }}">
                    <i class="fas fa-newspaper"></i>
                    Articles
                </a>
            </li>
            {% if is_granted('ROLE_ADMIN') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ path('app_new_article') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                    Ecrire un article
                </a>
            </li>
            {% endif %}
           

        </ul>

        {% if is_granted('ROLE_USER') %}
        <ul class="navbar-nav ml-auto">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user"></i>
                    Profil
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{ path('app_profile', {"id": userInter.id}) }}">Mon Profil</a>
                    <a class="dropdown-item" href="{{ path('app_new_article') }}">Ecrire un article</a>
                    <a class="dropdown-item" href="{{ path('app_article') }}">Mes articles</a>


                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ path('app_logout') }}">Déconnexion</a>
                </div>
            </li>
        </ul>



        {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-3">
                <a class="nav-link" href="{{ path('app_register') }}">
                    <i class="fas fa-user-plus mx-2"></i>
                    inscription
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ path('app_login') }}">
                    <i class="fas fa-sign-in-alt mx-2"></i>
                    connexion
                </a>
            </li>
        </ul>
        {% endif %}


    </div>
</nav>

projet_symfony/templates/partials/single_article.html.twig
<article class="d-flex flex-column align-items-center text-center">
    <!-- Post header-->
    <header class="mb-4">
        <!-- Post title-->
        <h1 class="fw-bolder mb-1">{{articles.title}}</h1>
    </header>
    <!-- Preview image figure-->
    <figure class="mb-4"><img class="img-fluid rounded" src="{{articles.image}}" alt="..." /></figure>
    <!-- Post content-->
    <section class="mb-5">
        <p class="fs-5 mb-4">{{articles.intro}}</p>
        <p class="fs-5 mb-4">{{articles.content}}</p>
        <a href="#" class="card-link">Auteur: {{article.author.username}}</a>
        <h2 class="fw-bolder mb-4 mt-5">{{articles.createdAt |date('d-m-Y') }}</h2>
    </section>
</article>